- name: Create new inventory
  hosts: localhost
  gather_facts: no
  vars:
    tower_host:
    inventory_name:
    inventory_description:
    inventory_organization:
    inventory_credential:
  tasks:
    - name: Get organization ID
      uri:
        url: "{{ tower_host }}/api/v2/organizations/?name={{ inventory_organization }}"
        method: GET
        user: bhargav
        password: bhar@123
        force_basic_auth: true
        validate_certs: no
      register: org_response

    - name: Create new inventory
      uri:
        url: "{{ tower_host }}/api/v2/inventories/"
        method: POST
        user: bhargav
        password: bhar@123
        force_basic_auth: true
        validate_certs: no
        body_format: json
        body:
          name: "{{ inventory_name }}"
          description: "{{ inventory_description }}"
          organization: "{{ org_response.json.results[0].id }}"
        status_code:
         - 200
         - 201
         - 202
         - 204
      register: inventory_response

    - name: Print inventory ID
      debug:
        var: inventory_response.json.id
