- name: Create new inventory
  hosts: localhost
  gather_facts: no
  vars:
    tower_host:
    inventory_name:
    inventory_description:
    inventory_organization:
    jumphost_group_name:
    group_variables_jh:
    vms_group_name:
    group_variables_vm:
  tasks:
    - name: Get organization ID
      uri:
        url: "{{ tower_host }}/api/v2/organizations/?name={{ inventory_organization }}"
        method: GET
        user: bhargav
        password: bhar@123
        force_basic_auth: true
        validate_certs: no
      register: org_response

    - name: Create new inventory
      uri:
        url: "{{ tower_host }}/api/v2/inventories/"
        method: POST
        user: bhargav
        password: bhar@123
        force_basic_auth: true
        validate_certs: no
        body_format: json
        body:
          name: "{{ inventory_name }}"
          description: "{{ inventory_description }}"
          organization: "{{ org_response.json.results[0].id }}"
        status_code:
         - 200
         - 201
         - 202
         - 204
      register: inventory_response

    - name: Print inventory ID
      debug:
        var: inventory_response.json.id


    - name: Create jumphost group in the same inventory
      uri:
        url: "{{ tower_host }}/api/v2/groups/"
        method: POST
        user: bhargav
        password: bhar@123
        force_basic_auth: true
        validate_certs: no
        body_format: json
        body:
          name: "{{ jumphost_group_name }}"
          inventory: "{{ inventory_response.json.id }}"
          variables: "{{ group_variables_jh }}"
        status_code:
          - 200
          - 201
          - 202
          - 204
      register: jumphost_group_response

    - name: Create 'vms' group in the same inventory
      uri:
        url: "{{ tower_host }}/api/v2/groups/"
        method: POST
        user: bhargav
        password: bhar@123
        force_basic_auth: true
        validate_certs: no
        body_format: json
        body:
          name: "{{ vms_group_name }}"
          inventory: "{{ inventory_response.json.id }}"
          variables: "{{ group_variables_vm }}"
        status_code:
          - 200
          - 201
          - 202
          - 204
      register: vms_group_response

    - name: Print 'jumphost' group ID
      debug:
        var: jumphost_group_response.json.id

    - name: Print 'vms' group ID
      debug:
        var: vms_group_response.json.id
